[build]
target = "armv7-unknown-linux-gnueabi"

[target.armv7-unknown-linux-gnueabi]
linker = "../libopenlipc-sys/Amazon-Kindle-Cross-Toolchain/arm-kindle-linux-gnueabi/bin/arm-kindle-linux-gnueabi-cc"
